### ISSUE TITLE
Not working in 5.0.0

### ISSUE THREAD

**Issue by ori-shiro** [greisane/gret#31]
helloo i know the 5.0.0 update has been recent and i dont know if you're already working on an updated gret add on. i think because its 5.0.0 the add-on isn't working, coming up instead with 'cannot create 'gpushader' instances'. I tried looking it up and all it said was that it was probably not compatible with newer versions. again idk if you're already working on it and i dont mean to sound pushy lmao

<img width="666" height="93" alt="Image" src="https://github.com/user-attachments/assets/c4894dd5-bfc0-4e49-99a5-b670f0051fe9" />

<img width="514" height="107" alt="Image" src="https://github.com/user-attachments/assets/0cd9cf8a-4ba6-46a5-be46-1de196d6977c" />

**Comment by VRBat** [comment]
Greisane hasn't had any github activity since 2024. You can use [deviandice's pull request](https://github.com/greisane/gret/tree/4b0ba58c69779ea3d7c6ea3b8b27fcd69d506a62) for now. It works fine in 5.0 

https://github.com/greisane/gret/pull/27

**Comment by TakaMonster1996** [comment]
same i cant get it to load due to this gpushader crap, and i use to use gret just fine before ,,,

**Comment by deviandice** [comment]
@VRBat Glad to know it's still working in 5.0 too.

**Comment by VanFanelMX** [comment]
Not working on Blender 5.1.

**Comment by deviandice** [comment]
> Not working on Blender 5.1.

Any chance you can be more specific about the issue? If you can, there's an equal chance I'll have a nosy at the issue.

**Comment by VanFanelMX** [comment]
> > Not working on Blender 5.1.
> 
> Any chance you can be more specific about the issue? If you can, there's an equal chance I'll have a nosy at the issue.

I tried to do some "relax loops" in UV editor and then got an error.

Python: Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\5.1\scripts\addons\gret-4b0ba58c69779ea3d7c6ea3b8b27fcd69d506a62\uv\relax_loops.py", line 86, in execute
    for loop in get_selection_loops(bm):
                ~~~~~~~~~~~~~~~~~~~^^^^
  File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\5.1\scripts\addons\gret-4b0ba58c69779ea3d7c6ea3b8b27fcd69d506a62\uv\helpers.py", line 111, in get_selection_loops
    bags = get_selection_bags(bm)
  File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\5.1\scripts\addons\gret-4b0ba58c69779ea3d7c6ea3b8b27fcd69d506a62\uv\helpers.py", line 57, in get_selection_bags
    if not loopuv.select:
           ^^^^^^^^^^^^^
AttributeError: 'BMLoopUV' object has no attribute 'select'
